---
- name: Backup Network Devices
  connection: network_cli
  hosts: lab
  gather_facts: no
  vars:
    ansible_network_os: ios
    ansible_ssh_user: ins 
    ansible_ssh_pass: ins@lab

  tasks:
    - name: backup device
      block:
      - name: register running-config
        cli_command:
          command: show running-config
        register: config
      - name: save running-config
        copy:
          content: "{{ config.stdout }}"
          dest: "{{ ansible_ssh_host }}.bck"
      - name: remove non Config Lines
        lineinfile:
          path: "{{ ansible_ssh_host }}.bck"
          line: "Building configuration..."
          state: absent
      - name: remove non Config Lines - REGEXP
        lineinfile:
          path: "{{ ansible_ssh_host }}.bck"
          regexp: 'Current configuration.*'
          state: absent
      - name: remove NTP clock-period lines
        lineinfile:
          path: "{{ ansible_ssh_host }}.bck"
          regexp: 'ntp clock-period*'
          state: absent